import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import '../../../assets/css/Report.css';
import { API_BASE_URL } from '../../../api';

const ReportPage = () => {
    const { student_usn } = useParams();
    const [report, setReport] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchReport = async () => {
            try {
                setLoading(true);
                const token = sessionStorage.getItem('access_token');
                const response = await fetch(`${API_BASE_URL}/student/${student_usn}/swot-report`, {
                    headers: {
                        'Authorization': `Bearer ${token}`,
                        'Content-Type': 'application/json'
                    }
                });
                if (!response.ok) {
                    throw new Error('Failed to fetch report');
                }
                const data = await response.json();
                
                // Check if the data contains the necessary SWOT fields
                if (data.strengths || data.weaknesses || data.opportunities || data.threats) {
                    setReport(data);
                } else {
                    setReport({}); // Set an empty object if no relevant data is found
                }
            } catch (error) {
                console.error('Error fetching the report:', error);
                setError(error.message);
            } finally {
                setLoading(false);
            }
        };

        fetchReport();
    }, [student_usn]);

    if (loading) {
        return (
            <div className="report-loading">
                <div className="loading-spinner"></div>
                <p>Generating your comprehensive report...</p>
            </div>
        );
    }

    if (error) {
        return (
            <div className="report-error">
                <div className="error-icon">⚠️</div>
                <h2>Error Loading Report</h2>
                <p>{error}</p>
                <button onClick={() => window.location.reload()} className="retry-btn">
                    Try Again
                </button>
            </div>
        );
    }

    if (!report || Object.keys(report).length === 0) {
        return (
            <div className="report-empty">
                <div className="empty-icon">📊</div>
                <h3>No Report Available</h3>
                <p>Your SWOT analysis report will be generated by your mentor after completing the assessment.</p>
            </div>
        );
    }

    return (
        <div className="report-page">
            {/* Header Section */}
            <div className="report-header">
                <div className="header-content">
                    <h1 className="page-title">Student Analysis Report</h1>
                    <p className="page-subtitle">Comprehensive SWOT analysis and personal insights</p>
                </div>
                <div className="student-usn">
                    <span className="usn-text">{student_usn}</span>
                </div>

            </div>

            {/* SWOT Analysis Grid */}
            <div className="swot-section">
                <h2 className="section-title">SWOT Analysis</h2>
                <div className="swot-grid">
                    <div className="swot-card strengths">
                        <div className="card-header">
                            <div className="card-icon">💪</div>
                            <h3>Strengths</h3>
                        </div>
                        <div className="card-content">
                            <p>{report.strengths || 'No strengths identified yet.'}</p>
                        </div>
                    </div>

                    <div className="swot-card opportunities">
                        <div className="card-header">
                            <div className="card-icon">🎯</div>
                            <h3>Opportunities</h3>
                        </div>
                        <div className="card-content">
                            <p>{report.opportunities || 'No opportunities identified yet.'}</p>
                        </div>
                    </div>

                    <div className="swot-card weaknesses">
                        <div className="card-header">
                            <div className="card-icon">⚠️</div>
                            <h3>Weaknesses</h3>
                        </div>
                        <div className="card-content">
                            <p>{report.weaknesses || 'No weaknesses identified yet.'}</p>
                        </div>
                    </div>

                    <div className="swot-card threats">
                        <div className="card-header">
                            <div className="card-icon">🚨</div>
                            <h3>Threats</h3>
                        </div>
                        <div className="card-content">
                            <p>{report.threats || 'No threats identified yet.'}</p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Additional Information */}
            <div className="additional-section">
                <h2 className="section-title">Personal Insights</h2>
                <div className="insights-grid">
                    {report.professional_aspirations && (
                        <div className="insight-card">
                            <div className="insight-header">
                                <div className="insight-icon">🎯</div>
                                <h3>Professional Aspirations</h3>
                            </div>
                            <p>{report.professional_aspirations}</p>
                        </div>
                    )}

                    {report['hobbies/interests'] && (
                        <div className="insight-card">
                            <div className="insight-header">
                                <div className="insight-icon">🎨</div>
                                <h3>Hobbies & Interests</h3>
                            </div>
                            <p>{report['hobbies/interests']}</p>
                        </div>
                    )}

                    {report.detailed_analysis && (
                        <div className="insight-card">
                            <div className="insight-header">
                                <div className="insight-icon">📊</div>
                                <h3>Detailed Analysis</h3>
                            </div>
                            <p>{report.detailed_analysis}</p>
                        </div>
                    )}
                </div>
            </div>

            {/* Report Footer */}
            <div className="report-footer">
                <div className="footer-content">
                    <p>Report generated for {student_usn}</p>
                    <p>Last updated: {new Date().toLocaleDateString()}</p>
                </div>
            </div>
        </div>
    );
};

export default ReportPage;
