import React, { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import '../../../assets/css/LoggedActivities.css';
import { API_BASE_URL } from "../../../api";

const StudentLoggedActivities = () => {
  const { student_usn } = useParams();
  const [activities, setActivities] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [selectedFilter, setSelectedFilter] = useState('all');
  const [searchTerm, setSearchTerm] = useState('');

  useEffect(() => {
    const fetchLoggedActivities = async () => {
      try {
        const response = await fetch(`${API_BASE_URL}/student/${student_usn}/logged_activities`);
        if (!response.ok) {
          if (response.status === 404) {
            setActivities([]);
          } else {
            throw new Error("Failed to fetch activities");
          }
        } else {
          const data = await response.json();
          setActivities(data.activities);
        }
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };
    
    fetchLoggedActivities();
  }, [student_usn]);

  const getDurationColor = (durationType) => {
    switch (durationType?.toLowerCase()) {
      case 'short term': return '#4CAF50';
      case 'mid term': return '#FF9800';
      case 'long term': return '#F44336';
      default: return '#9E9E9E';
    }
  };

  const getStatusColor = (status) => {
    switch (status?.toLowerCase()) {
      case 'approved': return '#4CAF50';
      case 'pending': return '#FF9800';
      case 'rejected': return '#F44336';
      case 'completed': return '#2196F3';
      default: return '#9E9E9E';
    }
  };

  // Handle different data structures and arrange by duration type in rows
  const getActivityCards = () => {
    if (!activities || activities.length === 0) {
      return [];
    }

    // Create exactly 3 activity slots (1 per type: Short Term, Mid Term, Long Term)
    const activitySlots = new Array(3).fill(null);
    
    // Separate activities by duration type
    const shortTermActivity = activities.find(activity => 
      activity.duration_type?.toLowerCase().includes('short')
    );
    const midTermActivity = activities.find(activity => 
      activity.duration_type?.toLowerCase().includes('mid')
    );
    const longTermActivity = activities.find(activity => 
      activity.duration_type?.toLowerCase().includes('long')
    );
    
    // Fill slot 0 with Short Term activity
    if (shortTermActivity) {
      activitySlots[0] = {
        ...shortTermActivity,
        isPlaceholder: false
      };
    } else {
      activitySlots[0] = {
        activity_id: 'placeholder-0',
        activities: 'No Activity Assigned',
        duration_type: 'Short Term',
        status: 'Not Started',
        isPlaceholder: true
      };
    }
    
    // Fill slot 1 with Mid Term activity
    if (midTermActivity) {
      activitySlots[1] = {
        ...midTermActivity,
        isPlaceholder: false
      };
    } else {
      activitySlots[1] = {
        activity_id: 'placeholder-1',
        activities: 'No Activity Assigned',
        duration_type: 'Mid Term',
        status: 'Not Started',
        isPlaceholder: true
      };
    }
    
    // Fill slot 2 with Long Term activity
    if (longTermActivity) {
      activitySlots[2] = {
        ...longTermActivity,
        isPlaceholder: false
      };
    } else {
      activitySlots[2] = {
        activity_id: 'placeholder-2',
        activities: 'No Activity Assigned',
        duration_type: 'Long Term',
        status: 'Not Started',
        isPlaceholder: true
      };
    }

    return activitySlots;
  };

  const activityCards = getActivityCards();
  
  if (loading) {
    return (
      <div className="logged-activities-loading">
        <div className="loading-spinner"></div>
        <p>Loading your logged activities...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="logged-activities-error">
        <div className="error-icon">⚠️</div>
        <h2>Error Loading Activities</h2>
        <p>{error}</p>
        <button onClick={() => window.location.reload()} className="retry-btn">
          Try Again
        </button>
      </div>
    );
  }

  if (activityCards.length === 0) {
    return (
      <div className="logged-activities-empty">
        <div className="empty-icon">📝</div>
        <h3>No activities logged yet</h3>
        <p>Your activities will appear here once they are generated by your mentor.</p>
      </div>
    );
  }
  
  const filteredActivities = selectedFilter === 'all' 
    ? activityCards 
    : activityCards.filter(activity => 
        !activity.isPlaceholder && 
        activity.duration_type?.toLowerCase().includes(selectedFilter.toLowerCase())
      );

  // If filtering results in no activities, show all cards
  const displayActivities = filteredActivities.length > 0 ? filteredActivities : activityCards;

  return (
    <div className="logged-activities-page">
      {/* Header Section */}
      <div className="logged-activities-header">
        <div className="header-content">
          <h1 className="page-title">My Logged Activities</h1>
          <p className="page-subtitle">Track your progress and completed activities</p>
        </div>
        <div className="student-usn">
          <span className="usn-text">{student_usn}</span>
        </div>

      </div>

      {/* Stats Cards */}
      <div className="stats-container">
        <div className="stat-card">
          <div className="stat-icon">📋</div>
          <div className="stat-content">
            <h3>{activities.length}</h3>
            <p>Total Activities</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon">✅</div>
          <div className="stat-content">
            <h3>{activities.filter(a => a.status === 'Completed').length}</h3>
            <p>Completed</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon">⏳</div>
          <div className="stat-content">
            <h3>{activities.filter(a => a.status === 'Pending').length}</h3>
            <p>In Progress</p>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon">📊</div>
          <div className="stat-content">
            <h3>{activities.filter(a => a.percentage).length}</h3>
            <p>Graded</p>
          </div>
        </div>
      </div>

      {/* Filters and Search */}
      <div className="filters-section">
        <div className="search-box">
          <input
            type="text"
            placeholder="Search activities..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="search-input"
          />
          <span className="search-icon">🔍</span>
        </div>
        <div className="filter-buttons">
          <button
            className={`filter-btn ${selectedFilter === 'all' ? 'active' : ''}`}
            onClick={() => setSelectedFilter('all')}
          >
            All
          </button>
          <button
            className={`filter-btn ${selectedFilter === 'short' ? 'active' : ''}`}
            onClick={() => setSelectedFilter('short')}
          >
            Short Term
          </button>
          <button
            className={`filter-btn ${selectedFilter === 'mid' ? 'active' : ''}`}
            onClick={() => setSelectedFilter('mid')}
          >
            Mid Term
          </button>
          <button
            className={`filter-btn ${selectedFilter === 'long' ? 'active' : ''}`}
            onClick={() => setSelectedFilter('long')}
          >
            Long Term
          </button>
        </div>
      </div>

      {/* Activities Grid - 3x3 Layout by Duration Type */}
      <div className="activities-grid">
        {displayActivities.map((activity, index) => (
          <div key={activity.activity_id} className={`activity-card ${activity.isPlaceholder ? 'placeholder' : ''}`}>
            <div className="card-header">
              <div className="activity-id">
                <span className="id-label">#{activity.activity_id}</span>
              </div>
              <div 
                className="duration-badge"
                style={{ backgroundColor: getDurationColor(activity.duration_type) }}
              >
                {activity.duration_type}
              </div>
            </div>
            
            <div className="card-content">
              <h3 className="activity-title">{activity.activities}</h3>
              
              {!activity.isPlaceholder && (
                <>


                  <div className="activity-details">
                    {activity.completed_in && (
                      <div className="detail-item">
                        <span className="detail-label">Completed in:</span>
                        <span className="detail-value">{activity.completed_in} days</span>
                      </div>
                    )}
                    
                    {activity.percentage && (
                      <div className="detail-item">
                        <span className="detail-label">Score:</span>
                        <span className="detail-value">{activity.percentage}%</span>
                      </div>
                    )}

                    {activity.remarks && (
                      <div className="detail-item">
                        <span className="detail-label">Remarks:</span>
                        <span className="detail-value">{activity.remarks}</span>
                      </div>
                    )}
                  </div>

                  <div className="activity-status">
                    <span 
                      className="status-badge"
                      style={{ backgroundColor: getStatusColor(activity.status) }}
                    >
                      {activity.status || 'Not Started'}
                    </span>
                  </div>
                </>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default StudentLoggedActivities;
